language: node_js
node_js:
- '4.6'
- '6.10'
- '7.2'
cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
- yarn report-coverage
deploy:
  - provider: heroku
    app: ctrlp-api
    on:
      repo: SharathKudikyala/APIDemo
      node: '7.2'
    api_key: f9a27842-a41f-4e67-84f4-df3e8936d7d9